# Generated by Django 5.0.1 on 2024-01-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_userprofile_following_alter_userprofile_follwers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro_bio',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='intro_body',
            field=models.CharField(default='Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident', max_length=200),
        ),
    ]
