# Generated by Django 5.0.1 on 2024-01-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_userprofile_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intro_bio',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', max_length=150),
        ),
    ]
