# Generated by Django 5.0.1 on 2024-01-19 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('notfication_date', models.DateTimeField(auto_now_add=True)),
                ('notification_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notification_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notfications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
