# Generated by Django 5.0.1 on 2024-01-19 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.post'),
        ),
    ]
