# Generated by Django 5.0.1 on 2024-01-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_notification_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notfication_date',
            new_name='notification_date',
        ),
    ]
